/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c49",
        "inverse-surface": "#e0e3e5",
        "tertiary-fixed": "#d5e3fd",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-bright": "#363a3b",
        "on-tertiary-container": "#2c3a4e",
        "tertiary-container": "#95a4bb",
        "secondary-container": "#3f465c",
        "surface-container-highest": "#323537",
        "primary-container": "#10b981",
        "surface-variant": "#323537",
        "surface-tint": "#4edea3",
        "on-surface-variant": "#bbcabf",
        "outline": "#86948a",
        "on-tertiary": "#233144",
        "surface-container-low": "#191c1e",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#b9c7e0",
        "inverse-on-surface": "#2d3133",
        "on-error": "#690005",
        "outline-variant": "#3c4a42",
        "surface": "#101415",
        "on-secondary": "#283044",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container": "#1d2022",
        "on-primary-container": "#00422b",
        "on-primary": "#003824",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#0d1c2f",
        "primary": "#4edea3",
        "tertiary": "#b9c7e0",
        "background": "#101415",
        "on-secondary-container": "#adb4ce",
        "secondary": "#bec6e0",
        "on-primary-fixed": "#002113",
        "on-surface": "#e0e3e5",
        "on-background": "#e0e3e5",
        "surface-container-lowest": "#0b0f10",
        "on-secondary-fixed": "#131b2e",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#005236",
        "surface-container-high": "#272a2c",
        "surface-dim": "#101415",
        "on-secondary-fixed-variant": "#3f465c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full-custom": "0.75rem" // we name this full-custom to avoid breaking tailwind's rounded-full (9999px)
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1200px",
        "stack-md": "24px",
        "stack-sm": "8px",
        "stack-lg": "80px",
        "section-padding": "120px",
        "gutter": "32px"
      },
      fontFamily: {
        "headline-lg": ["Sora", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "nav-link": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-code": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "nav-link": ["14px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
